/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esiee.mbdaihm.view;

/**
 *
 * @author Sébastien Hu
 */
public class testJPanel extends javax.swing.JPanel {

    /**
     * Creates new form testJPanel
     */
    public testJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_frame = new javax.swing.JFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_region = new javax.swing.JMenu();
        region_europe = new javax.swing.JCheckBoxMenuItem();
        region_asie = new javax.swing.JCheckBoxMenuItem();
        region_afrique = new javax.swing.JCheckBoxMenuItem();
        region_nord_amerique = new javax.swing.JCheckBoxMenuItem();
        region_sud_amerique = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        menu_donnees = new javax.swing.JMenu();
        menu_periode = new javax.swing.JMenu();
        menu_type = new javax.swing.JMenu();
        menu_sauvegarder = new javax.swing.JMenu();
        menu_charger = new javax.swing.JMenu();
        jDialog1 = new javax.swing.JDialog();

        menu_region.setText("Région");

        region_europe.setSelected(true);
        region_europe.setText("Europe");
        region_europe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                region_europeActionPerformed(evt);
            }
        });
        menu_region.add(region_europe);

        region_asie.setSelected(true);
        region_asie.setText("Asie");
        region_asie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                region_asieActionPerformed(evt);
            }
        });
        menu_region.add(region_asie);

        region_afrique.setSelected(true);
        region_afrique.setText("Afrique");
        menu_region.add(region_afrique);

        region_nord_amerique.setSelected(true);
        region_nord_amerique.setText("Amérique du Nord");
        menu_region.add(region_nord_amerique);

        region_sud_amerique.setSelected(true);
        region_sud_amerique.setText("Amérique du Sud");
        menu_region.add(region_sud_amerique);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Océanie");
        menu_region.add(jCheckBoxMenuItem1);

        jMenuBar1.add(menu_region);

        menu_donnees.setText("Données");
        jMenuBar1.add(menu_donnees);

        menu_periode.setText("Période");
        jMenuBar1.add(menu_periode);

        menu_type.setText("Type");
        jMenuBar1.add(menu_type);

        menu_sauvegarder.setText("Sauvegarder");
        jMenuBar1.add(menu_sauvegarder);

        menu_charger.setText("Charger");
        jMenuBar1.add(menu_charger);

        main_frame.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout main_frameLayout = new javax.swing.GroupLayout(main_frame.getContentPane());
        main_frame.getContentPane().setLayout(main_frameLayout);
        main_frameLayout.setHorizontalGroup(
            main_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        main_frameLayout.setVerticalGroup(
            main_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void region_europeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_region_europeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_region_europeActionPerformed

    private void region_asieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_region_asieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_region_asieActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JFrame main_frame;
    private javax.swing.JMenu menu_charger;
    private javax.swing.JMenu menu_donnees;
    private javax.swing.JMenu menu_periode;
    private javax.swing.JMenu menu_region;
    private javax.swing.JMenu menu_sauvegarder;
    private javax.swing.JMenu menu_type;
    private javax.swing.JCheckBoxMenuItem region_afrique;
    private javax.swing.JCheckBoxMenuItem region_asie;
    private javax.swing.JCheckBoxMenuItem region_europe;
    private javax.swing.JCheckBoxMenuItem region_nord_amerique;
    private javax.swing.JCheckBoxMenuItem region_sud_amerique;
    // End of variables declaration//GEN-END:variables
}
